/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Card } from "@pax2pay/model-cde";
import { Error } from "gracely";
export { Card } from "@pax2pay/model-cde";
export { Error } from "gracely";
export namespace Components {
    interface P2pCdeButton {
        "card"?: Card.Token | Error;
        "holder"?: string;
        "nameAlreadyEncoded": boolean;
        "task": "print" | "pdf";
    }
    interface P2pCdeDemo {
    }
    interface P2pCdeDisplay {
        "card"?: Card.Token | Error;
        "cardPart": "pan" | "csc" | "expires";
        "feature"?: "copy";
        "format"?: "plain" | "labelled";
    }
    interface P2pCdeInput {
    }
    interface P2pCdeKeyGenerate {
        "getPublicKey": () => Promise<string | false>;
    }
    interface P2pVirtualCard {
        "card"?: Card.Token | Error;
        "cardHolderName"?: string;
        "company"?: string;
        "height": string;
        "nameAlreadyEncoded": boolean;
        "width": string;
    }
}
declare global {
    interface HTMLP2pCdeButtonElement extends Components.P2pCdeButton, HTMLStencilElement {
    }
    var HTMLP2pCdeButtonElement: {
        prototype: HTMLP2pCdeButtonElement;
        new (): HTMLP2pCdeButtonElement;
    };
    interface HTMLP2pCdeDemoElement extends Components.P2pCdeDemo, HTMLStencilElement {
    }
    var HTMLP2pCdeDemoElement: {
        prototype: HTMLP2pCdeDemoElement;
        new (): HTMLP2pCdeDemoElement;
    };
    interface HTMLP2pCdeDisplayElement extends Components.P2pCdeDisplay, HTMLStencilElement {
    }
    var HTMLP2pCdeDisplayElement: {
        prototype: HTMLP2pCdeDisplayElement;
        new (): HTMLP2pCdeDisplayElement;
    };
    interface HTMLP2pCdeInputElement extends Components.P2pCdeInput, HTMLStencilElement {
    }
    var HTMLP2pCdeInputElement: {
        prototype: HTMLP2pCdeInputElement;
        new (): HTMLP2pCdeInputElement;
    };
    interface HTMLP2pCdeKeyGenerateElement extends Components.P2pCdeKeyGenerate, HTMLStencilElement {
    }
    var HTMLP2pCdeKeyGenerateElement: {
        prototype: HTMLP2pCdeKeyGenerateElement;
        new (): HTMLP2pCdeKeyGenerateElement;
    };
    interface HTMLP2pVirtualCardElement extends Components.P2pVirtualCard, HTMLStencilElement {
    }
    var HTMLP2pVirtualCardElement: {
        prototype: HTMLP2pVirtualCardElement;
        new (): HTMLP2pVirtualCardElement;
    };
    interface HTMLElementTagNameMap {
        "p2p-cde-button": HTMLP2pCdeButtonElement;
        "p2p-cde-demo": HTMLP2pCdeDemoElement;
        "p2p-cde-display": HTMLP2pCdeDisplayElement;
        "p2p-cde-input": HTMLP2pCdeInputElement;
        "p2p-cde-key-generate": HTMLP2pCdeKeyGenerateElement;
        "p2p-virtual-card": HTMLP2pVirtualCardElement;
    }
}
declare namespace LocalJSX {
    interface P2pCdeButton {
        "card"?: Card.Token | Error;
        "holder"?: string;
        "nameAlreadyEncoded"?: boolean;
        "task"?: "print" | "pdf";
    }
    interface P2pCdeDemo {
    }
    interface P2pCdeDisplay {
        "card"?: Card.Token | Error;
        "cardPart"?: "pan" | "csc" | "expires";
        "feature"?: "copy";
        "format"?: "plain" | "labelled";
    }
    interface P2pCdeInput {
    }
    interface P2pCdeKeyGenerate {
    }
    interface P2pVirtualCard {
        "card"?: Card.Token | Error;
        "cardHolderName"?: string;
        "company"?: string;
        "height"?: string;
        "nameAlreadyEncoded"?: boolean;
        "width"?: string;
    }
    interface IntrinsicElements {
        "p2p-cde-button": P2pCdeButton;
        "p2p-cde-demo": P2pCdeDemo;
        "p2p-cde-display": P2pCdeDisplay;
        "p2p-cde-input": P2pCdeInput;
        "p2p-cde-key-generate": P2pCdeKeyGenerate;
        "p2p-virtual-card": P2pVirtualCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "p2p-cde-button": LocalJSX.P2pCdeButton & JSXBase.HTMLAttributes<HTMLP2pCdeButtonElement>;
            "p2p-cde-demo": LocalJSX.P2pCdeDemo & JSXBase.HTMLAttributes<HTMLP2pCdeDemoElement>;
            "p2p-cde-display": LocalJSX.P2pCdeDisplay & JSXBase.HTMLAttributes<HTMLP2pCdeDisplayElement>;
            "p2p-cde-input": LocalJSX.P2pCdeInput & JSXBase.HTMLAttributes<HTMLP2pCdeInputElement>;
            "p2p-cde-key-generate": LocalJSX.P2pCdeKeyGenerate & JSXBase.HTMLAttributes<HTMLP2pCdeKeyGenerateElement>;
            "p2p-virtual-card": LocalJSX.P2pVirtualCard & JSXBase.HTMLAttributes<HTMLP2pVirtualCardElement>;
        }
    }
}
